### ISSUE TITLE
Settings Page with Light/Dark Mode Switch

### ISSUE THREAD

**Issue by Malte2036** [Malte2036/react-social#1]
To implement the dark and lightmode switch look here :moon: : https://github.com/Malte2036/react-social/blob/main/lib/database/backendService.ts#L53

**Comment by Gumanpratapsingh** [comment]
Please Assign this issue to me
I would love to work upon this.

**Comment by Malte2036** [comment]
> Please Assign this issue to me I would love to work upon this.

@indiehjaerta is working on this one.
