### ISSUE TITLE
Google Social Login (frontend)

### ISSUE THREAD

**Issue by Malte2036** [Malte2036/react-social#2]

**Comment by Malte2036** [comment]
Also see: https://github.com/Malte2036/react-social-backend/issues/1

**Comment by spykelionel** [comment]
Oh. Looks good

**Comment by Malte2036** [comment]
@spykelionel I think it would be best to implement the social login on the frontend side. then send the google token to the backend to validate and login there. 

Take a look here: https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by spykelionel** [comment]
I see
