### ISSUE TITLE
Add Multifunctional Toast Notifications

### ISSUE THREAD

**Issue by Malte2036** [Malte2036/react-social#6]
Replace "alert()" with an error Toast bar.

**Comment by UtkarshM-hub** [comment]
@Malte2036 Is anyone working on this issue?

**Comment by Malte2036** [comment]
You can work on this one

**Comment by ArnabDey1543** [comment]
@Malte2036 can you please assign me this work ?

**Comment by UtkarshM-hub** [comment]
@Malte2036 I think instead of making the toast just for error messages we should make it multifunctional. like it should be able to show error, success , info and warning message just by providing what type of toast we want to display.

**Comment by Malte2036** [comment]
> @Malte2036 can you please assign me this work ?
> 

@UtkarshM-hub is already assigned to this issue.

**Comment by Malte2036** [comment]
> @Malte2036 I think instead of making the toast just for error messages we should make it multifunctional. like it should be able to show error, success , info and warning message just by providing what type of toast we want to display.

Good idea 👍. I changed the title.
